## Load Data

In [2]:
!ls -lh /content

total 157M
-rw-r--r-- 1 root root 157M Dec 12 18:09 favorita_model_ready.parquet
drwxr-xr-x 1 root root 4.0K Dec 11 14:34 sample_data

In [1]:
import pandas as pd

df = pd.read_parquet("/content/favorita_model_ready_2013_2015.parquet")

In [2]:
df.shape

(13913510, 27)

In [3]:
df.columns

Index(['id', 'date', 'store_nbr', 'item_nbr', 'unit_sales', 'onpromotion',
       'family', 'class', 'perishable', 'city', 'state', 'type', 'cluster',
       'dcoilwtico', 'description', 'transactions', 'year', 'month',
       'dayofweek', 'weekofyear', 'is_weekend', 'is_holiday', 'lag_7',
       'lag_14', 'lag_28', 'rolling_7', 'rolling_14'],
      dtype='object')

In [4]:
df.tail()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,family,class,perishable,city,...,month,dayofweek,weekofyear,is_weekend,is_holiday,lag_7,lag_14,lag_28,rolling_7,rolling_14
13913505,66368775,2015-12-31,4,314570,6.0,0,CLEANING,3024,0,Quito,...,12,3,53,0,1,9.0,5.0,3.0,6.142857,6.500000
13913506,66442398,2015-12-31,46,841514,3.0,0,GROCERY I,1072,0,Quito,...,12,3,53,0,1,10.0,7.0,7.0,15.142857,13.428571
13913507,66427101,2015-12-31,38,1146802,8.0,0,GROCERY I,1040,0,Loja,...,12,3,53,0,1,3.0,7.0,3.0,4.000000,5.285714
13913508,66368777,2015-12-31,4,315176,8.0,0,BEVERAGES,1124,0,Quito,...,12,3,53,0,1,4.0,4.0,21.0,10.142857,12.642857
13913509,66455563,2015-12-31,51,2026983,16.0,0,GROCERY I,1034,0,Guayaquil,...,12,3,53,0,1,31.0,28.0,18.0,24.285714,52.357143

In [5]:
df['date'].dtype

dtype('<M8[ns]')

In [22]:
FEATURES = [
    # identifiers
    "store_nbr",
    "item_nbr",

    # categorical structure
    "family",
    "class",
    "city",
    "cluster",

    # promotions & ops
    "onpromotion",
    "transactions",
    "perishable",

    # calendar
    "month",
    "dayofweek",
    "weekofyear",
    "is_weekend",

    # external signals
    "dcoilwtico",
    "is_holiday",

    # time-series features
    "lag_7",
    "lag_14",
    "lag_28",
    "rolling_7",
    "rolling_14"
]

CATEGORICAL_FEATURES = [
    "store_nbr",
    "item_nbr",
    "family",
    "class",
    "city",
    "cluster"
]

for col in CATEGORICAL_FEATURES:
    df[col] = df[col].astype("category")

TARGET = "unit_sales"

## Time-aware Train/Test Split

In [23]:
cutoff_date = "2017-06-01"

train_df = df[df["date"] < cutoff_date]
valid_df = df[df["date"] >= cutoff_date]

len(train_df), len(valid_df)

(6023898, 397009)

## Define features and target

In [8]:
df.columns

Index(['id', 'date', 'store_nbr', 'item_nbr', 'unit_sales', 'onpromotion',
       'family', 'class', 'perishable', 'city', 'state', 'type', 'cluster',
       'dcoilwtico', 'description', 'transactions', 'year', 'month',
       'dayofweek', 'weekofyear', 'is_weekend', 'is_holiday', 'lag_7',
       'lag_14', 'lag_28', 'rolling_7', 'rolling_14'],
      dtype='object')

In [24]:
X_train = train_df[FEATURES]
y_train = train_df[TARGET]

X_valid = valid_df[FEATURES]
y_valid = valid_df[TARGET]

In [25]:
print("Train rows:", X_train.shape[0])
print("Valid rows:", X_valid.shape[0])

print("\nCategorical dtypes:")
print(X_train[CATEGORICAL_FEATURES].dtypes)

Train rows: 6023898
Valid rows: 397009

Categorical dtypes:
store_nbr    category
item_nbr     category
family       category
class        category
city         category
cluster      category
dtype: object

In [26]:
import lightgbm as lgb

model = lgb.LGBMRegressor(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train,
    y_train,
    categorical_feature=CATEGORICAL_FEATURES,
    eval_set=[(X_valid, y_valid)],
    eval_metric="rmse"
)

[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.070604 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Info] Start training from score 30.225520

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.05, n_estimators=300,
              n_jobs=-1, num_leaves=64, random_state=42, subsample=0.8)

In [27]:
import numpy as np
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_valid)
rmse = np.sqrt(mean_squared_error(y_valid, y_pred))

rmse

np.float64(27.81019894933662)

In [29]:
baseline_pred = X_valid["lag_7"]

baseline_rmse = np.sqrt(
    mean_squared_error(y_valid, baseline_pred)
)

baseline_rmse

np.float64(40.005072406250434)

In [30]:
baseline_pred_roll = X_valid["rolling_7"]

baseline_rmse_roll = np.sqrt(
    mean_squared_error(y_valid, baseline_pred_roll)
)

baseline_rmse_roll

np.float64(32.21615596576178)

In [32]:
from sklearn.metrics import mean_squared_log_error

y_pred = pd.Series(y_pred, index=y_valid.index)

rmsle = np.sqrt(
    mean_squared_log_error(
        y_valid.clip(lower=0),
        y_pred.clip(lower=0)
    )
)

rmsle

np.float64(0.5330477146416599)

## Log-target LightGBM training + RMSLE evaluation

In [33]:
y_train_log = np.log1p(y_train)
y_valid_log = np.log1p(y_valid)

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [34]:
model_log = lgb.LGBMRegressor(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

model_log.fit(
    X_train,
    y_train_log,
    categorical_feature=CATEGORICAL_FEATURES,
    eval_set=[(X_valid, y_valid_log)],
    eval_metric="rmse",
    callbacks=[
        lgb.early_stopping(stopping_rounds=30),
        lgb.log_evaluation(period=50)
    ]
)

[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.477590 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Info] Start training from score -680622392496873871147351714824192.000000
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[1]	valid_0's rmse: 2.7489e+35	valid_0's l2: 7.55645e+70

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.05, n_estimators=500,
              n_jobs=-1, num_leaves=64, random_state=42, subsample=0.8)

In [39]:
y_pred_log = model_log.predict(
    X_valid,
    num_iteration=model_log.best_iteration_
)

y_pred = np.expm1(y_pred_log)

In [40]:
rmse = np.sqrt(mean_squared_error(y_valid, y_pred))

rmsle = np.sqrt(
    mean_squared_log_error(
        y_valid.clip(lower=0),
        np.clip(y_pred, 0, None)
    )
)

rmse, rmsle

(np.float64(61.37445519554005), np.float64(3.0354103239073713))

In [41]:
y_valid.describe()

count    397009.000000
mean         29.944653
std          53.002446
min        -274.000000
25%           8.000000
50%          16.000000
75%          33.000000
max        6932.000000
Name: unit_sales, dtype: float64

In [42]:
y_valid.head()

6023898    23.0
6023899     3.0
6023900    44.0
6023901     4.0
6023902     6.0
Name: unit_sales, dtype: float64

In [43]:
np.allclose(y_valid, np.log1p(np.expm1(y_valid)))

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in expm1
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

False

In [44]:
y_train_raw = train_df["unit_sales"].values
y_valid_raw = valid_df["unit_sales"].values

In [45]:
y_train_raw = np.clip(y_train_raw, 0, None)
y_valid_raw = np.clip(y_valid_raw, 0, None)

In [46]:
y_train_log = np.log1p(y_train_raw)
y_valid_log = np.log1p(y_valid_raw)

In [47]:
model_log = lgb.LGBMRegressor(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

model_log.fit(
    X_train,
    y_train_log,
    categorical_feature=CATEGORICAL_FEATURES,
    eval_set=[(X_valid, y_valid_log)],
    eval_metric="rmse",
    callbacks=[
        lgb.early_stopping(stopping_rounds=30),
        lgb.log_evaluation(period=50)
    ]
)

[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.685559 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
[50]	valid_0's rmse: 0.517537	valid_0's l2: 0.267845
[100]	valid_0's rmse: 0.502294	valid_0's l2: 0.252299
[150]	valid_0's rmse: 0.497813	valid_0's l2: 0.247818
[200]	valid_0's rmse: 0.495501	valid_0's l2: 0.245521
[250]	valid_0's rmse: 0.493939	valid_0's l2: 0.243976
[300]	valid_0's rmse: 0.49306	valid_0's l2: 0.243108
[350]	valid_0's rmse: 0.492301	valid_0's l2: 0.24236
[400]	valid_0's rmse: 0.491754	valid_0's l2: 0.241822
[450]	valid_0's rmse: 0.491263	valid_0's l2: 0.241339
[500]	valid_0's rmse: 0.490871	valid_0's l2: 0.240954
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.490871	valid_0's l2: 0.240954

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.05, n_estimators=500,
              n_jobs=-1, num_leaves=64, random_state=42, subsample=0.8)

In [48]:
# Predict in log space using best iteration
y_pred_log = model_log.predict(
    X_valid,
    num_iteration=model_log.best_iteration_
)

# Invert log transform
y_pred = np.expm1(y_pred_log)

In [49]:
from sklearn.metrics import mean_squared_error, mean_squared_log_error
import numpy as np

# RMSE (original scale)
rmse_log_model = np.sqrt(
    mean_squared_error(y_valid_raw, y_pred)
)

# RMSLE (primary metric)
rmsle_log_model = np.sqrt(
    mean_squared_log_error(
        y_valid_raw,
        np.clip(y_pred, 0, None)
    )
)

rmse_log_model, rmsle_log_model

(np.float64(28.47586464861986), np.float64(0.49087099129589895))

## Optuna + ML FLow Hyperparameter Tuning

In [50]:
!pip install mlflow
!pip install optuna

Collecting mlflow
  Downloading mlflow-3.7.0-py3-none-any.whl.metadata (31 kB)
Collecting mlflow-skinny==3.7.0 (from mlflow)
  Downloading mlflow_skinny-3.7.0-py3-none-any.whl.metadata (31 kB)
Collecting mlflow-tracing==3.7.0 (from mlflow)
  Downloading mlflow_tracing-3.7.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.1-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.2)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.17.2)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<24 (from mlflow)
  Downloading gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)
Collecting huey<3,>=2.5.0 (from mlflow)
  Downloading huey-2.5.5-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<23,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.44)
Requirement already satisfied: cachetools<7,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (6.2.2)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.7.0->mlflow)
  Downloading databricks_sdk-0.74.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (0.118.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (3.1.45)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (8.7.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (1.37.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (1.37.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (1.37.0)
Requirement already satisfied: packaging<26 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (25.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (5.29.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (0.5.4)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.7.0->mlflow) (0.38.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.4)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.7-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.2.5)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (2.23)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.7.0->mlflow) (2.43.0)
Requirement already satisfied: starlette<0.49.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.7.0->mlflow) (0.48.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.7.0->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.7.0->mlflow) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.58b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.7.0->mlflow) (0.58b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.7.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.7.0->mlflow) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.7.0->mlflow) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.7.0->mlflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.7.0->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.7.0->mlflow) (2025.11.12)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.7.0->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.7.0->mlflow) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.7.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.7.0->mlflow) (4.9.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette<0.49.0,>=0.40.0->fastapi<1->mlflow-skinny==3.7.0->mlflow) (4.12.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.7.0->mlflow) (0.6.1)
Downloading mlflow-3.7.0-py3-none-any.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 42.0 MB/s eta 0:00:00
Downloading mlflow_skinny-3.7.0-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 58.9 MB/s eta 0:00:00
Downloading mlflow_tracing-3.7.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 45.5 MB/s eta 0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 9.8 MB/s eta 0:00:00
Downloading flask_cors-6.0.1-py3-none-any.whl (13 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 6.7 MB/s eta 0:00:00
Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 5.3 MB/s eta 0:00:00
Downloading huey-2.5.5-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.9/76.9 kB 5.4 MB/s eta 0:00:00
Downloading databricks_sdk-0.74.0-py3-none-any.whl (764 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 764.2/764.2 kB 24.3 MB/s eta 0:00:00
Downloading graphql_core-3.2.7-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 13.6 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Installing collected packages: huey, gunicorn, graphql-core, graphql-relay, docker, graphene, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
Successfully installed Flask-CORS-6.0.1 databricks-sdk-0.74.0 docker-7.1.0 graphene-3.4.3 graphql-core-3.2.7 graphql-relay-3.2.0 gunicorn-23.0.0 huey-2.5.5 mlflow-3.7.0 mlflow-skinny-3.7.0 mlflow-tracing-3.7.0
Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 7.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0

In [51]:
import optuna
import mlflow
import mlflow.lightgbm

def objective_lgb(trial):
    params = {
        "n_estimators": 500,
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1),
        "num_leaves": trial.suggest_int("num_leaves", 31, 127),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 50, 300),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.7, 1.0),
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.7, 1.0),
        "random_state": 42,
        "n_jobs": -1
    }

    with mlflow.start_run(nested=True):
        model = lgb.LGBMRegressor(**params)

        model.fit(
            X_train,
            y_train_log,
            categorical_feature=CATEGORICAL_FEATURES,
            eval_set=[(X_valid, y_valid_log)],
            eval_metric="rmse",
            callbacks=[lgb.early_stopping(30)]
        )

        y_pred_log = model.predict(
            X_valid,
            num_iteration=model.best_iteration_
        )
        y_pred = np.expm1(y_pred_log)

        rmsle = np.sqrt(
            mean_squared_log_error(
                y_valid_raw,
                np.clip(y_pred, 0, None)
            )
        )

        mlflow.log_params(params)
        mlflow.log_metric("rmsle", rmsle)

        return rmsle

In [52]:
study = optuna.create_study(direction="minimize")
study.optimize(objective_lgb, n_trials=25)

[I 2025-12-12 19:15:28,058] A new study created in memory with name: no-name-fc2af93b-03cc-4d5e-a616-fee8fe90ecac
2025/12/12 19:15:34 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/12/12 19:15:34 INFO mlflow.store.db.utils: Updating database tables
2025/12/12 19:15:34 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/12 19:15:34 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade  -> 451aebb31d03, add metric step
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
2025/12/12 19:15:34 INFO alembic.runtime.migration: Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 0584bdc529eb -> 400f98739977, add logged model tables
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 400f98739977 -> 6953534de441, add step to inputs table
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade 6953534de441 -> bda7b8c39065, increase_model_version_tag_value_limit
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade bda7b8c39065 -> cbc13b556ace, add V3 trace schema columns
2025/12/12 19:15:35 INFO alembic.runtime.migration: Running upgrade cbc13b556ace -> 770bee3ae1dd, add assessments table
2025/12/12 19:15:36 INFO alembic.runtime.migration: Running upgrade 770bee3ae1dd -> a1b2c3d4e5f6, add spans table
2025/12/12 19:15:36 INFO alembic.runtime.migration: Running upgrade a1b2c3d4e5f6 -> de4033877273, create entity_associations table
2025/12/12 19:15:36 INFO alembic.runtime.migration: Running upgrade de4033877273 -> 1a0cddfcaa16, Add webhooks and webhook_events tables
2025/12/12 19:15:36 INFO alembic.runtime.migration: Running upgrade 1a0cddfcaa16 -> 534353b11cbc, add scorer tables
2025/12/12 19:15:36 INFO alembic.runtime.migration: Running upgrade 534353b11cbc -> 71994744cf8e, add evaluation datasets
2025/12/12 19:15:36 INFO alembic.runtime.migration: Running upgrade 71994744cf8e -> 3da73c924c2f, add outputs to dataset record
2025/12/12 19:15:36 INFO alembic.runtime.migration: Running upgrade 3da73c924c2f -> bf29a5ff90ea, add jobs table
2025/12/12 19:15:36 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/12 19:15:36 INFO alembic.runtime.migration: Will assume non-transactional DDL.

[LightGBM] [Warning] min_data_in_leaf is set=155, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=155
[LightGBM] [Warning] feature_fraction is set=0.8972879877179761, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8972879877179761
[LightGBM] [Warning] bagging_fraction is set=0.9583256115739262, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9583256115739262
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=155, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=155
[LightGBM] [Warning] feature_fraction is set=0.8972879877179761, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8972879877179761
[LightGBM] [Warning] bagging_fraction is set=0.9583256115739262, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9583256115739262
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.947390 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=155, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=155
[LightGBM] [Warning] feature_fraction is set=0.8972879877179761, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8972879877179761
[LightGBM] [Warning] bagging_fraction is set=0.9583256115739262, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9583256115739262
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.491647	valid_0's l2: 0.241717
[LightGBM] [Warning] feature_fraction is set=0.8972879877179761, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8972879877179761
[LightGBM] [Warning] min_data_in_leaf is set=155, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=155
[LightGBM] [Warning] bagging_fraction is set=0.9583256115739262, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9583256115739262

[I 2025-12-12 19:22:40,859] Trial 0 finished with value: 0.4916474211101287 and parameters: {'learning_rate': 0.06264692393663822, 'num_leaves': 42, 'min_data_in_leaf': 155, 'feature_fraction': 0.8972879877179761, 'bagging_fraction': 0.9583256115739262}. Best is trial 0 with value: 0.4916474211101287.

[LightGBM] [Warning] min_data_in_leaf is set=160, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=160
[LightGBM] [Warning] feature_fraction is set=0.9465922702389011, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9465922702389011
[LightGBM] [Warning] bagging_fraction is set=0.8118665658361347, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8118665658361347
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=160, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=160
[LightGBM] [Warning] feature_fraction is set=0.9465922702389011, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9465922702389011
[LightGBM] [Warning] bagging_fraction is set=0.8118665658361347, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8118665658361347
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.393392 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=160, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=160
[LightGBM] [Warning] feature_fraction is set=0.9465922702389011, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9465922702389011
[LightGBM] [Warning] bagging_fraction is set=0.8118665658361347, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8118665658361347
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[498]	valid_0's rmse: 0.48894	valid_0's l2: 0.239062
[LightGBM] [Warning] feature_fraction is set=0.9465922702389011, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9465922702389011
[LightGBM] [Warning] min_data_in_leaf is set=160, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=160
[LightGBM] [Warning] bagging_fraction is set=0.8118665658361347, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8118665658361347

[I 2025-12-12 19:33:27,936] Trial 1 finished with value: 0.48893979834312773 and parameters: {'learning_rate': 0.057840792030508056, 'num_leaves': 112, 'min_data_in_leaf': 160, 'feature_fraction': 0.9465922702389011, 'bagging_fraction': 0.8118665658361347}. Best is trial 1 with value: 0.48893979834312773.

[LightGBM] [Warning] min_data_in_leaf is set=249, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=249
[LightGBM] [Warning] feature_fraction is set=0.7106046440973075, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7106046440973075
[LightGBM] [Warning] bagging_fraction is set=0.9644105665420135, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9644105665420135
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=249, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=249
[LightGBM] [Warning] feature_fraction is set=0.7106046440973075, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7106046440973075
[LightGBM] [Warning] bagging_fraction is set=0.9644105665420135, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9644105665420135
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.985242 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=249, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=249
[LightGBM] [Warning] feature_fraction is set=0.7106046440973075, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7106046440973075
[LightGBM] [Warning] bagging_fraction is set=0.9644105665420135, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9644105665420135
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.49437	valid_0's l2: 0.244402
[LightGBM] [Warning] feature_fraction is set=0.7106046440973075, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7106046440973075
[LightGBM] [Warning] min_data_in_leaf is set=249, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=249
[LightGBM] [Warning] bagging_fraction is set=0.9644105665420135, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9644105665420135

[I 2025-12-12 19:45:05,882] Trial 2 finished with value: 0.4943701766224847 and parameters: {'learning_rate': 0.014904263269694108, 'num_leaves': 117, 'min_data_in_leaf': 249, 'feature_fraction': 0.7106046440973075, 'bagging_fraction': 0.9644105665420135}. Best is trial 1 with value: 0.48893979834312773.

[LightGBM] [Warning] min_data_in_leaf is set=300, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=300
[LightGBM] [Warning] feature_fraction is set=0.9667121609089739, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9667121609089739
[LightGBM] [Warning] bagging_fraction is set=0.8520850501423938, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8520850501423938
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=300, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=300
[LightGBM] [Warning] feature_fraction is set=0.9667121609089739, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9667121609089739
[LightGBM] [Warning] bagging_fraction is set=0.8520850501423938, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8520850501423938
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.602688 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=300, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=300
[LightGBM] [Warning] feature_fraction is set=0.9667121609089739, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9667121609089739
[LightGBM] [Warning] bagging_fraction is set=0.8520850501423938, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8520850501423938
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.489253	valid_0's l2: 0.239369
[LightGBM] [Warning] feature_fraction is set=0.9667121609089739, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9667121609089739
[LightGBM] [Warning] min_data_in_leaf is set=300, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=300
[LightGBM] [Warning] bagging_fraction is set=0.8520850501423938, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8520850501423938

[I 2025-12-12 19:55:30,244] Trial 3 finished with value: 0.4892533345960407 and parameters: {'learning_rate': 0.05319789050301207, 'num_leaves': 110, 'min_data_in_leaf': 300, 'feature_fraction': 0.9667121609089739, 'bagging_fraction': 0.8520850501423938}. Best is trial 1 with value: 0.48893979834312773.

[LightGBM] [Warning] min_data_in_leaf is set=290, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=290
[LightGBM] [Warning] feature_fraction is set=0.8446991733464316, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8446991733464316
[LightGBM] [Warning] bagging_fraction is set=0.8819420397158948, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8819420397158948
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=290, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=290
[LightGBM] [Warning] feature_fraction is set=0.8446991733464316, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8446991733464316
[LightGBM] [Warning] bagging_fraction is set=0.8819420397158948, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8819420397158948
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.422405 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=290, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=290
[LightGBM] [Warning] feature_fraction is set=0.8446991733464316, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8446991733464316
[LightGBM] [Warning] bagging_fraction is set=0.8819420397158948, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8819420397158948
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[495]	valid_0's rmse: 0.488688	valid_0's l2: 0.238816
[LightGBM] [Warning] feature_fraction is set=0.8446991733464316, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8446991733464316
[LightGBM] [Warning] min_data_in_leaf is set=290, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=290
[LightGBM] [Warning] bagging_fraction is set=0.8819420397158948, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8819420397158948

[I 2025-12-12 20:04:08,391] Trial 4 finished with value: 0.48868792605792055 and parameters: {'learning_rate': 0.08603084031561181, 'num_leaves': 94, 'min_data_in_leaf': 290, 'feature_fraction': 0.8446991733464316, 'bagging_fraction': 0.8819420397158948}. Best is trial 4 with value: 0.48868792605792055.

[LightGBM] [Warning] min_data_in_leaf is set=295, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=295
[LightGBM] [Warning] feature_fraction is set=0.9945595238611862, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9945595238611862
[LightGBM] [Warning] bagging_fraction is set=0.9386512827455578, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9386512827455578
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=295, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=295
[LightGBM] [Warning] feature_fraction is set=0.9945595238611862, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9945595238611862
[LightGBM] [Warning] bagging_fraction is set=0.9386512827455578, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9386512827455578
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.658863 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=295, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=295
[LightGBM] [Warning] feature_fraction is set=0.9945595238611862, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9945595238611862
[LightGBM] [Warning] bagging_fraction is set=0.9386512827455578, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9386512827455578
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[496]	valid_0's rmse: 0.493258	valid_0's l2: 0.243303
[LightGBM] [Warning] feature_fraction is set=0.9945595238611862, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9945595238611862
[LightGBM] [Warning] min_data_in_leaf is set=295, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=295
[LightGBM] [Warning] bagging_fraction is set=0.9386512827455578, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9386512827455578

[I 2025-12-12 20:12:53,811] Trial 5 finished with value: 0.49325787180815345 and parameters: {'learning_rate': 0.03178565163880253, 'num_leaves': 60, 'min_data_in_leaf': 295, 'feature_fraction': 0.9945595238611862, 'bagging_fraction': 0.9386512827455578}. Best is trial 4 with value: 0.48868792605792055.

[LightGBM] [Warning] min_data_in_leaf is set=163, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=163
[LightGBM] [Warning] feature_fraction is set=0.7123909262216858, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7123909262216858
[LightGBM] [Warning] bagging_fraction is set=0.9149128638756197, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9149128638756197
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=163, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=163
[LightGBM] [Warning] feature_fraction is set=0.7123909262216858, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7123909262216858
[LightGBM] [Warning] bagging_fraction is set=0.9149128638756197, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9149128638756197
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.755171 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=163, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=163
[LightGBM] [Warning] feature_fraction is set=0.7123909262216858, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7123909262216858
[LightGBM] [Warning] bagging_fraction is set=0.9149128638756197, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9149128638756197
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.491488	valid_0's l2: 0.24156
[LightGBM] [Warning] feature_fraction is set=0.7123909262216858, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7123909262216858
[LightGBM] [Warning] min_data_in_leaf is set=163, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=163
[LightGBM] [Warning] bagging_fraction is set=0.9149128638756197, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9149128638756197

[I 2025-12-12 20:18:47,485] Trial 6 finished with value: 0.4914877010883164 and parameters: {'learning_rate': 0.09869352495971859, 'num_leaves': 34, 'min_data_in_leaf': 163, 'feature_fraction': 0.7123909262216858, 'bagging_fraction': 0.9149128638756197}. Best is trial 4 with value: 0.48868792605792055.

[LightGBM] [Warning] min_data_in_leaf is set=284, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=284
[LightGBM] [Warning] feature_fraction is set=0.9357735667270861, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9357735667270861
[LightGBM] [Warning] bagging_fraction is set=0.9305068275055282, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9305068275055282
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=284, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=284
[LightGBM] [Warning] feature_fraction is set=0.9357735667270861, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9357735667270861
[LightGBM] [Warning] bagging_fraction is set=0.9305068275055282, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9305068275055282
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.407782 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=284, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=284
[LightGBM] [Warning] feature_fraction is set=0.9357735667270861, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9357735667270861
[LightGBM] [Warning] bagging_fraction is set=0.9305068275055282, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9305068275055282
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.492443	valid_0's l2: 0.2425
[LightGBM] [Warning] feature_fraction is set=0.9357735667270861, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9357735667270861
[LightGBM] [Warning] min_data_in_leaf is set=284, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=284
[LightGBM] [Warning] bagging_fraction is set=0.9305068275055282, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9305068275055282

[I 2025-12-12 20:25:55,817] Trial 7 finished with value: 0.4924433858762469 and parameters: {'learning_rate': 0.06663938370934776, 'num_leaves': 33, 'min_data_in_leaf': 284, 'feature_fraction': 0.9357735667270861, 'bagging_fraction': 0.9305068275055282}. Best is trial 4 with value: 0.48868792605792055.

[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.777446 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[463]	valid_0's rmse: 0.488113	valid_0's l2: 0.238255
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944

[I 2025-12-12 20:34:59,873] Trial 8 finished with value: 0.48811331852399 and parameters: {'learning_rate': 0.09556996173730738, 'num_leaves': 120, 'min_data_in_leaf': 143, 'feature_fraction': 0.8889602666162978, 'bagging_fraction': 0.723716991047944}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=239, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=239
[LightGBM] [Warning] feature_fraction is set=0.7548649975898856, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7548649975898856
[LightGBM] [Warning] bagging_fraction is set=0.7762614611173638, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7762614611173638
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=239, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=239
[LightGBM] [Warning] feature_fraction is set=0.7548649975898856, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7548649975898856
[LightGBM] [Warning] bagging_fraction is set=0.7762614611173638, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7762614611173638
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.446005 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=239, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=239
[LightGBM] [Warning] feature_fraction is set=0.7548649975898856, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7548649975898856
[LightGBM] [Warning] bagging_fraction is set=0.7762614611173638, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7762614611173638
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.490861	valid_0's l2: 0.240944
[LightGBM] [Warning] feature_fraction is set=0.7548649975898856, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7548649975898856
[LightGBM] [Warning] min_data_in_leaf is set=239, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=239
[LightGBM] [Warning] bagging_fraction is set=0.7762614611173638, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7762614611173638

[I 2025-12-12 20:45:53,916] Trial 9 finished with value: 0.4908605977856182 and parameters: {'learning_rate': 0.02816915930279231, 'num_leaves': 107, 'min_data_in_leaf': 239, 'feature_fraction': 0.7548649975898856, 'bagging_fraction': 0.7762614611173638}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] feature_fraction is set=0.8226999387574984, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8226999387574984
[LightGBM] [Warning] bagging_fraction is set=0.704926692931746, subsample=1.0 will be ignored. Current value: bagging_fraction=0.704926692931746
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] feature_fraction is set=0.8226999387574984, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8226999387574984
[LightGBM] [Warning] bagging_fraction is set=0.704926692931746, subsample=1.0 will be ignored. Current value: bagging_fraction=0.704926692931746
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.034851 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] feature_fraction is set=0.8226999387574984, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8226999387574984
[LightGBM] [Warning] bagging_fraction is set=0.704926692931746, subsample=1.0 will be ignored. Current value: bagging_fraction=0.704926692931746
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[499]	valid_0's rmse: 0.489159	valid_0's l2: 0.239277
[LightGBM] [Warning] feature_fraction is set=0.8226999387574984, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8226999387574984
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] bagging_fraction is set=0.704926692931746, subsample=1.0 will be ignored. Current value: bagging_fraction=0.704926692931746

[I 2025-12-12 20:53:55,203] Trial 10 finished with value: 0.48915935354704293 and parameters: {'learning_rate': 0.08143927103563009, 'num_leaves': 78, 'min_data_in_leaf': 85, 'feature_fraction': 0.8226999387574984, 'bagging_fraction': 0.704926692931746}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=99, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=99
[LightGBM] [Warning] feature_fraction is set=0.8479776024547149, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8479776024547149
[LightGBM] [Warning] bagging_fraction is set=0.8680585150102559, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8680585150102559
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=99, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=99
[LightGBM] [Warning] feature_fraction is set=0.8479776024547149, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8479776024547149
[LightGBM] [Warning] bagging_fraction is set=0.8680585150102559, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8680585150102559
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.339586 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=99, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=99
[LightGBM] [Warning] feature_fraction is set=0.8479776024547149, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8479776024547149
[LightGBM] [Warning] bagging_fraction is set=0.8680585150102559, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8680585150102559
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.488341	valid_0's l2: 0.238477
[LightGBM] [Warning] feature_fraction is set=0.8479776024547149, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8479776024547149
[LightGBM] [Warning] min_data_in_leaf is set=99, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=99
[LightGBM] [Warning] bagging_fraction is set=0.8680585150102559, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8680585150102559

[I 2025-12-12 21:01:48,567] Trial 11 finished with value: 0.4883409232373951 and parameters: {'learning_rate': 0.09798304758998747, 'num_leaves': 89, 'min_data_in_leaf': 99, 'feature_fraction': 0.8479776024547149, 'bagging_fraction': 0.8680585150102559}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=90, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=90
[LightGBM] [Warning] feature_fraction is set=0.8849109626337343, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8849109626337343
[LightGBM] [Warning] bagging_fraction is set=0.7149016927493487, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7149016927493487
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=90, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=90
[LightGBM] [Warning] feature_fraction is set=0.8849109626337343, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8849109626337343
[LightGBM] [Warning] bagging_fraction is set=0.7149016927493487, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7149016927493487
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.660259 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=90, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=90
[LightGBM] [Warning] feature_fraction is set=0.8849109626337343, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8849109626337343
[LightGBM] [Warning] bagging_fraction is set=0.7149016927493487, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7149016927493487
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[494]	valid_0's rmse: 0.488608	valid_0's l2: 0.238737
[LightGBM] [Warning] feature_fraction is set=0.8849109626337343, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8849109626337343
[LightGBM] [Warning] min_data_in_leaf is set=90, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=90
[LightGBM] [Warning] bagging_fraction is set=0.7149016927493487, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7149016927493487

[I 2025-12-12 21:09:11,315] Trial 12 finished with value: 0.4886075527382752 and parameters: {'learning_rate': 0.0992743359908893, 'num_leaves': 86, 'min_data_in_leaf': 90, 'feature_fraction': 0.8849109626337343, 'bagging_fraction': 0.7149016927493487}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=55, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=55
[LightGBM] [Warning] feature_fraction is set=0.8019069022124058, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8019069022124058
[LightGBM] [Warning] bagging_fraction is set=0.774343329577592, subsample=1.0 will be ignored. Current value: bagging_fraction=0.774343329577592
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=55, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=55
[LightGBM] [Warning] feature_fraction is set=0.8019069022124058, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8019069022124058
[LightGBM] [Warning] bagging_fraction is set=0.774343329577592, subsample=1.0 will be ignored. Current value: bagging_fraction=0.774343329577592
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.360646 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=55, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=55
[LightGBM] [Warning] feature_fraction is set=0.8019069022124058, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8019069022124058
[LightGBM] [Warning] bagging_fraction is set=0.774343329577592, subsample=1.0 will be ignored. Current value: bagging_fraction=0.774343329577592
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.488127	valid_0's l2: 0.238268
[LightGBM] [Warning] feature_fraction is set=0.8019069022124058, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8019069022124058
[LightGBM] [Warning] min_data_in_leaf is set=55, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=55
[LightGBM] [Warning] bagging_fraction is set=0.774343329577592, subsample=1.0 will be ignored. Current value: bagging_fraction=0.774343329577592

[I 2025-12-12 21:18:56,335] Trial 13 finished with value: 0.48812670530778846 and parameters: {'learning_rate': 0.07899682105017036, 'num_leaves': 126, 'min_data_in_leaf': 55, 'feature_fraction': 0.8019069022124058, 'bagging_fraction': 0.774343329577592}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=127, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=127
[LightGBM] [Warning] feature_fraction is set=0.8052613058483977, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8052613058483977
[LightGBM] [Warning] bagging_fraction is set=0.7705031461229406, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7705031461229406
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=127, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=127
[LightGBM] [Warning] feature_fraction is set=0.8052613058483977, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8052613058483977
[LightGBM] [Warning] bagging_fraction is set=0.7705031461229406, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7705031461229406
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.376250 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=127, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=127
[LightGBM] [Warning] feature_fraction is set=0.8052613058483977, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8052613058483977
[LightGBM] [Warning] bagging_fraction is set=0.7705031461229406, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7705031461229406
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[484]	valid_0's rmse: 0.488326	valid_0's l2: 0.238462
[LightGBM] [Warning] feature_fraction is set=0.8052613058483977, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8052613058483977
[LightGBM] [Warning] min_data_in_leaf is set=127, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=127
[LightGBM] [Warning] bagging_fraction is set=0.7705031461229406, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7705031461229406

[I 2025-12-12 21:28:25,781] Trial 14 finished with value: 0.48832610058219367 and parameters: {'learning_rate': 0.07763669660391181, 'num_leaves': 127, 'min_data_in_leaf': 127, 'feature_fraction': 0.8052613058483977, 'bagging_fraction': 0.7705031461229406}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=57, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=57
[LightGBM] [Warning] feature_fraction is set=0.7851724397624936, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7851724397624936
[LightGBM] [Warning] bagging_fraction is set=0.7473744062079636, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7473744062079636
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=57, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=57
[LightGBM] [Warning] feature_fraction is set=0.7851724397624936, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7851724397624936
[LightGBM] [Warning] bagging_fraction is set=0.7473744062079636, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7473744062079636
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.087807 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=57, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=57
[LightGBM] [Warning] feature_fraction is set=0.7851724397624936, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7851724397624936
[LightGBM] [Warning] bagging_fraction is set=0.7473744062079636, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7473744062079636
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[499]	valid_0's rmse: 0.488443	valid_0's l2: 0.238576
[LightGBM] [Warning] feature_fraction is set=0.7851724397624936, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7851724397624936
[LightGBM] [Warning] min_data_in_leaf is set=57, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=57
[LightGBM] [Warning] bagging_fraction is set=0.7473744062079636, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7473744062079636

[I 2025-12-12 21:37:44,728] Trial 15 finished with value: 0.4884425204589454 and parameters: {'learning_rate': 0.07778085030303215, 'num_leaves': 125, 'min_data_in_leaf': 57, 'feature_fraction': 0.7851724397624936, 'bagging_fraction': 0.7473744062079636}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=51, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=51
[LightGBM] [Warning] feature_fraction is set=0.8841505788248663, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8841505788248663
[LightGBM] [Warning] bagging_fraction is set=0.8063711053205866, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8063711053205866
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=51, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=51
[LightGBM] [Warning] feature_fraction is set=0.8841505788248663, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8841505788248663
[LightGBM] [Warning] bagging_fraction is set=0.8063711053205866, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8063711053205866
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.922682 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=51, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=51
[LightGBM] [Warning] feature_fraction is set=0.8841505788248663, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8841505788248663
[LightGBM] [Warning] bagging_fraction is set=0.8063711053205866, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8063711053205866
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[497]	valid_0's rmse: 0.488763	valid_0's l2: 0.23889
[LightGBM] [Warning] feature_fraction is set=0.8841505788248663, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8841505788248663
[LightGBM] [Warning] min_data_in_leaf is set=51, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=51
[LightGBM] [Warning] bagging_fraction is set=0.8063711053205866, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8063711053205866

[I 2025-12-12 21:46:40,514] Trial 16 finished with value: 0.48876341114441946 and parameters: {'learning_rate': 0.08737334236472048, 'num_leaves': 102, 'min_data_in_leaf': 51, 'feature_fraction': 0.8841505788248663, 'bagging_fraction': 0.8063711053205866}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=199, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=199
[LightGBM] [Warning] feature_fraction is set=0.7584398055037638, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7584398055037638
[LightGBM] [Warning] bagging_fraction is set=0.738154539050649, subsample=1.0 will be ignored. Current value: bagging_fraction=0.738154539050649
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=199, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=199
[LightGBM] [Warning] feature_fraction is set=0.7584398055037638, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7584398055037638
[LightGBM] [Warning] bagging_fraction is set=0.738154539050649, subsample=1.0 will be ignored. Current value: bagging_fraction=0.738154539050649
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.950576 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=199, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=199
[LightGBM] [Warning] feature_fraction is set=0.7584398055037638, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7584398055037638
[LightGBM] [Warning] bagging_fraction is set=0.738154539050649, subsample=1.0 will be ignored. Current value: bagging_fraction=0.738154539050649
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.490931	valid_0's l2: 0.241013
[LightGBM] [Warning] feature_fraction is set=0.7584398055037638, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7584398055037638
[LightGBM] [Warning] min_data_in_leaf is set=199, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=199
[LightGBM] [Warning] bagging_fraction is set=0.738154539050649, subsample=1.0 will be ignored. Current value: bagging_fraction=0.738154539050649

[I 2025-12-12 21:55:27,827] Trial 17 finished with value: 0.49093070174479075 and parameters: {'learning_rate': 0.044447981982026895, 'num_leaves': 72, 'min_data_in_leaf': 199, 'feature_fraction': 0.7584398055037638, 'bagging_fraction': 0.738154539050649}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=193, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=193
[LightGBM] [Warning] feature_fraction is set=0.924984392959364, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.924984392959364
[LightGBM] [Warning] bagging_fraction is set=0.7829348690402974, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7829348690402974
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=193, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=193
[LightGBM] [Warning] feature_fraction is set=0.924984392959364, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.924984392959364
[LightGBM] [Warning] bagging_fraction is set=0.7829348690402974, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7829348690402974
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.631622 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=193, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=193
[LightGBM] [Warning] feature_fraction is set=0.924984392959364, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.924984392959364
[LightGBM] [Warning] bagging_fraction is set=0.7829348690402974, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7829348690402974
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[460]	valid_0's rmse: 0.489062	valid_0's l2: 0.239182
[LightGBM] [Warning] feature_fraction is set=0.924984392959364, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.924984392959364
[LightGBM] [Warning] min_data_in_leaf is set=193, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=193
[LightGBM] [Warning] bagging_fraction is set=0.7829348690402974, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7829348690402974

[I 2025-12-12 22:04:20,742] Trial 18 finished with value: 0.4890620494168843 and parameters: {'learning_rate': 0.0705523473600579, 'num_leaves': 119, 'min_data_in_leaf': 193, 'feature_fraction': 0.924984392959364, 'bagging_fraction': 0.7829348690402974}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] feature_fraction is set=0.8734406095355945, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8734406095355945
[LightGBM] [Warning] bagging_fraction is set=0.9992253415993728, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9992253415993728
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] feature_fraction is set=0.8734406095355945, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8734406095355945
[LightGBM] [Warning] bagging_fraction is set=0.9992253415993728, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9992253415993728
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.693260 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] feature_fraction is set=0.8734406095355945, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8734406095355945
[LightGBM] [Warning] bagging_fraction is set=0.9992253415993728, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9992253415993728
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.48876	valid_0's l2: 0.238886
[LightGBM] [Warning] feature_fraction is set=0.8734406095355945, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8734406095355945
[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] bagging_fraction is set=0.9992253415993728, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9992253415993728

[I 2025-12-12 22:12:57,375] Trial 19 finished with value: 0.48875971099831994 and parameters: {'learning_rate': 0.08825031364490937, 'num_leaves': 102, 'min_data_in_leaf': 126, 'feature_fraction': 0.8734406095355945, 'bagging_fraction': 0.9992253415993728}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=130, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=130
[LightGBM] [Warning] feature_fraction is set=0.7680838353703874, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7680838353703874
[LightGBM] [Warning] bagging_fraction is set=0.8088850720698467, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8088850720698467
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=130, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=130
[LightGBM] [Warning] feature_fraction is set=0.7680838353703874, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7680838353703874
[LightGBM] [Warning] bagging_fraction is set=0.8088850720698467, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8088850720698467
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.379642 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=130, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=130
[LightGBM] [Warning] feature_fraction is set=0.7680838353703874, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7680838353703874
[LightGBM] [Warning] bagging_fraction is set=0.8088850720698467, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8088850720698467
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[497]	valid_0's rmse: 0.488962	valid_0's l2: 0.239084
[LightGBM] [Warning] feature_fraction is set=0.7680838353703874, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7680838353703874
[LightGBM] [Warning] min_data_in_leaf is set=130, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=130
[LightGBM] [Warning] bagging_fraction is set=0.8088850720698467, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8088850720698467

[I 2025-12-12 22:21:22,092] Trial 20 finished with value: 0.4889621488463968 and parameters: {'learning_rate': 0.07290690071963109, 'num_leaves': 96, 'min_data_in_leaf': 130, 'feature_fraction': 0.7680838353703874, 'bagging_fraction': 0.8088850720698467}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] feature_fraction is set=0.8237317790559794, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8237317790559794
[LightGBM] [Warning] bagging_fraction is set=0.7509759554919165, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7509759554919165
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] feature_fraction is set=0.8237317790559794, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8237317790559794
[LightGBM] [Warning] bagging_fraction is set=0.7509759554919165, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7509759554919165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.380192 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] feature_fraction is set=0.8237317790559794, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8237317790559794
[LightGBM] [Warning] bagging_fraction is set=0.7509759554919165, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7509759554919165
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[499]	valid_0's rmse: 0.488554	valid_0's l2: 0.238685
[LightGBM] [Warning] feature_fraction is set=0.8237317790559794, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8237317790559794
[LightGBM] [Warning] min_data_in_leaf is set=126, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=126
[LightGBM] [Warning] bagging_fraction is set=0.7509759554919165, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7509759554919165

[I 2025-12-12 22:29:53,692] Trial 21 finished with value: 0.48855406847314187 and parameters: {'learning_rate': 0.09037068382876755, 'num_leaves': 126, 'min_data_in_leaf': 126, 'feature_fraction': 0.8237317790559794, 'bagging_fraction': 0.7509759554919165}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=107, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=107
[LightGBM] [Warning] feature_fraction is set=0.7963609736931693, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7963609736931693
[LightGBM] [Warning] bagging_fraction is set=0.7680037709221788, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7680037709221788
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=107, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=107
[LightGBM] [Warning] feature_fraction is set=0.7963609736931693, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7963609736931693
[LightGBM] [Warning] bagging_fraction is set=0.7680037709221788, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7680037709221788
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.757462 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=107, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=107
[LightGBM] [Warning] feature_fraction is set=0.7963609736931693, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7963609736931693
[LightGBM] [Warning] bagging_fraction is set=0.7680037709221788, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7680037709221788
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.488645	valid_0's l2: 0.238774
[LightGBM] [Warning] feature_fraction is set=0.7963609736931693, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7963609736931693
[LightGBM] [Warning] min_data_in_leaf is set=107, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=107
[LightGBM] [Warning] bagging_fraction is set=0.7680037709221788, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7680037709221788

[I 2025-12-12 22:39:19,786] Trial 22 finished with value: 0.48864469018855555 and parameters: {'learning_rate': 0.07844401581042017, 'num_leaves': 127, 'min_data_in_leaf': 107, 'feature_fraction': 0.7963609736931693, 'bagging_fraction': 0.7680037709221788}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=77, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=77
[LightGBM] [Warning] feature_fraction is set=0.8065856576712195, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8065856576712195
[LightGBM] [Warning] bagging_fraction is set=0.7185621601970078, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7185621601970078
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=77, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=77
[LightGBM] [Warning] feature_fraction is set=0.8065856576712195, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8065856576712195
[LightGBM] [Warning] bagging_fraction is set=0.7185621601970078, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7185621601970078
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.136673 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=77, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=77
[LightGBM] [Warning] feature_fraction is set=0.8065856576712195, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8065856576712195
[LightGBM] [Warning] bagging_fraction is set=0.7185621601970078, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7185621601970078
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[404]	valid_0's rmse: 0.488473	valid_0's l2: 0.238606
[LightGBM] [Warning] feature_fraction is set=0.8065856576712195, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8065856576712195
[LightGBM] [Warning] min_data_in_leaf is set=77, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=77
[LightGBM] [Warning] bagging_fraction is set=0.7185621601970078, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7185621601970078

[I 2025-12-12 22:46:53,045] Trial 23 finished with value: 0.4884729080404506 and parameters: {'learning_rate': 0.09192306908858203, 'num_leaves': 116, 'min_data_in_leaf': 77, 'feature_fraction': 0.8065856576712195, 'bagging_fraction': 0.7185621601970078}. Best is trial 8 with value: 0.48811331852399.

[LightGBM] [Warning] min_data_in_leaf is set=144, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=144
[LightGBM] [Warning] feature_fraction is set=0.8591273225296187, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8591273225296187
[LightGBM] [Warning] bagging_fraction is set=0.8320213227405258, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8320213227405258
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=144, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=144
[LightGBM] [Warning] feature_fraction is set=0.8591273225296187, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8591273225296187
[LightGBM] [Warning] bagging_fraction is set=0.8320213227405258, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8320213227405258
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.364252 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=144, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=144
[LightGBM] [Warning] feature_fraction is set=0.8591273225296187, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8591273225296187
[LightGBM] [Warning] bagging_fraction is set=0.8320213227405258, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8320213227405258
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.48886	valid_0's l2: 0.238984
[LightGBM] [Warning] feature_fraction is set=0.8591273225296187, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8591273225296187
[LightGBM] [Warning] min_data_in_leaf is set=144, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=144
[LightGBM] [Warning] bagging_fraction is set=0.8320213227405258, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8320213227405258

[I 2025-12-12 22:56:00,821] Trial 24 finished with value: 0.48885966312000734 and parameters: {'learning_rate': 0.07730947002773758, 'num_leaves': 120, 'min_data_in_leaf': 144, 'feature_fraction': 0.8591273225296187, 'bagging_fraction': 0.8320213227405258}. Best is trial 8 with value: 0.48811331852399.

In [53]:
import optuna
import joblib

# Save study to disk
joblib.dump(study, "optuna_lgb_study.pkl")

['optuna_lgb_study.pkl']

In [54]:
from google.colab import files
files.download("optuna_lgb_study.pkl")

In [55]:
best_params = study.best_trial.params
best_score = study.best_value

print("Best RMSLE:", best_score)
print("Best params:", best_params)

Best RMSLE: 0.48811331852399
Best params: {'learning_rate': 0.09556996173730738, 'num_leaves': 120, 'min_data_in_leaf': 143, 'feature_fraction': 0.8889602666162978, 'bagging_fraction': 0.723716991047944}

In [57]:
import lightgbm as lgb
import mlflow
import mlflow.lightgbm
import numpy as np
from sklearn.metrics import mean_squared_log_error

with mlflow.start_run(run_name="final_lgb_model"):

    final_model = lgb.LGBMRegressor(
        n_estimators=800,
        random_state=42,
        n_jobs=-1,
        **best_params
    )

    final_model.fit(
        X_train,
        y_train_log,
        categorical_feature=CATEGORICAL_FEATURES,
        eval_set=[(X_valid, y_valid_log)],
        eval_metric="rmse",
        callbacks=[
            lgb.early_stopping(stopping_rounds=50),
            lgb.log_evaluation(period=50)
        ]
    )

    # Predict & invert log
    y_pred_log = final_model.predict(X_valid)
    y_pred = np.expm1(y_pred_log)

    rmsle = np.sqrt(
        mean_squared_log_error(
            y_valid_raw,
            np.clip(y_pred, 0, None)
        )
    )

    mlflow.log_params(best_params)
    mlflow.log_metric("rmsle", rmsle)

    mlflow.lightgbm.log_model(
        final_model,
        artifact_path="model",
        registered_model_name="favorita_lgb"
    )

print("Final RMSLE:", rmsle)

[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.891814 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2571
[LightGBM] [Info] Number of data points in the train set: 6023898, number of used features: 20
[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944
[LightGBM] [Info] Start training from score 2.910365
Training until validation scores don't improve for 50 rounds
[50]	valid_0's rmse: 0.498882	valid_0's l2: 0.248883
[100]	valid_0's rmse: 0.492774	valid_0's l2: 0.242826
[150]	valid_0's rmse: 0.490861	valid_0's l2: 0.240945
[200]	valid_0's rmse: 0.489908	valid_0's l2: 0.240009
[250]	valid_0's rmse: 0.489226	valid_0's l2: 0.239342
[300]	valid_0's rmse: 0.4887	valid_0's l2: 0.238827
[350]	valid_0's rmse: 0.488406	valid_0's l2: 0.23854
[400]	valid_0's rmse: 0.488239	valid_0's l2: 0.238378
[450]	valid_0's rmse: 0.488168	valid_0's l2: 0.238308
[500]	valid_0's rmse: 0.488157	valid_0's l2: 0.238297
[550]	valid_0's rmse: 0.488139	valid_0's l2: 0.23828
[600]	valid_0's rmse: 0.488086	valid_0's l2: 0.238228
Early stopping, best iteration is:
[595]	valid_0's rmse: 0.488085	valid_0's l2: 0.238227
[LightGBM] [Warning] feature_fraction is set=0.8889602666162978, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8889602666162978
[LightGBM] [Warning] min_data_in_leaf is set=143, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=143
[LightGBM] [Warning] bagging_fraction is set=0.723716991047944, subsample=1.0 will be ignored. Current value: bagging_fraction=0.723716991047944

2025/12/12 23:25:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/12 23:25:20 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/12/12 23:25:20 INFO mlflow.store.db.utils: Updating database tables
2025/12/12 23:25:20 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/12 23:25:20 INFO alembic.runtime.migration: Will assume non-transactional DDL.

Final RMSLE: 0.48808458307225616

Successfully registered model 'favorita_lgb'.
Created version '1' of model 'favorita_lgb'.

In [58]:
final_model.booster_.save_model("favorita_lgb.txt")
files.download("favorita_lgb.txt")

In [59]:
import shutil

shutil.make_archive("mlflow_run", "zip", "mlruns")
files.download("mlflow_run.zip")

In [60]:
# Prepare test data
y_test_raw = np.clip(test_df["unit_sales"].values, 0, None)
X_test = test_df[FEATURES]

# Predict
y_test_log_pred = final_model.predict(X_test)
y_test_pred = np.expm1(y_test_log_pred)

test_rmsle = np.sqrt(
    mean_squared_log_error(y_test_raw, np.clip(y_test_pred, 0, None))
)

print("Test RMSLE:", test_rmsle)

mlflow.log_metric("test_rmsle", test_rmsle)

NameError: name 'test_df' is not defined